version: "3"

services:
  backend-centra:
    build:
      context: ./Backend-Centra-Window
      dockerfile: Dockerfile
    environment:
      - SENDEREMAIL=hthanhlong97@gmail.com
      # This password will be removed early
      - PASSWORD=pmxo ordi acvw ubga
    volumes:
      - ./Backend-Centra-Window/uploads/:/app/uploads
      - ./Backend-Centra-Window/output/:/app/output
    image: backend-centra:lastest
    container_name: backend-centra-container
    ports:
      - "8080:8080"
  frontend-centra:
    build:
      context: ./Centra-Window
      dockerfile: Dockerfile
    image: frontend-centra:lastest
    container_name: frontend-centra-container
    ports:
      - "80:80"
